services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    volumes:
      - .:/app
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
